## Table of contents
- The Basics and Array Creation in 2D
- Indexing and Slicing in 2D
- Basic Operations in 2D

In [1]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [4]:
import numpy as np
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
A.ndim

2

In [6]:
A.shape

(3, 3)

In [7]:
A.size

9

In [8]:
B = np.array([[1, 0, 1], [0, 1, 1]])
B.shape

(2, 3)

In [9]:
C = np.array([[1,0,1],[2,2,2]])
C[0, 1]

0

In [10]:
A[0, 0:2]

array([11, 12])

In [11]:
A[0:2, 2]

array([13, 23])

In [12]:
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])
Z  = X + Y
Z

array([[3, 1],
       [1, 3]])

In [13]:
W = 2 * Y
W

array([[4, 2],
       [2, 4]])

In [14]:
V = X * Y
V

array([[2, 0],
       [0, 2]])

In [18]:
D = np.array([[0, 1, 1], [1, 0, 1]])
E = np.array([[1, 1], [1, 1], [-1, 1]])
F =np.dot(D, E);
F

array([[0, 2],
       [0, 2]])

### Tests

In [19]:
G = np.array([[1, 0], [0, 1]])
H = np.array([[0, 1], [1, 0]])
I = G + H
I

array([[1, 1],
       [1, 1]])

In [22]:
J = np.array([[1, 0, 1], [2, 2, 2]])
out = J[0:2, 2]
out

array([1, 2])

In [23]:
K = np.array([[1, 0], [0, 1]])
L = np.array([[2, 2], [2, 2]])
M = np.dot(K, L)
M

array([[2, 2],
       [2, 2]])